export const FETCH_ALL_PROJECTS = "FETCH_ALL_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const FETCH_ONE_PROJECT = "FETCH_ONE_PROJECT";
export const DELETE_ONE_PROJECT = "DELETE_ONE_PROJECT";

export const FETCH_ALL_TASKS = "FETCH_ALL_TASKS";
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const FETCH_ONE_TASK = "FETCH_ONE_TASK";
export const DELETE_ONE_TASK = "DELETE_ONE_TASK";

export const FETCH_ALL_SUBTASKS = "FETCH_ALL_SUBTASKS";
export const CREATE_SUBTASK = "CREATE_SUBTASK";
export const UPDATE_SUBTASK = "UPDATE_SUBTASK";
export const FETCH_ONE_SUBTASK = "FETCH_ONE_SUBTASK";
export const DELETE_ONE_SUBTASK = "DELETE_ONE_SUBTASK";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const FETCH_ONE_USER = "FETCH_ONE_USER";
